image:
- Visual Studio 2015

environment:
  WXWIN: C:\wxWidgets-3.1.1
  wxWidgets_ROOT_DIR: $(WXWIN)
  wxWidgets_INCLUDE_DIRS: $(wxWidgets_ROOT_DIR)\include        
  configuration: Release 
  project_dir: c:\projects\wxAutoExcel
  
  matrix:
    - toolset: msbuild 
      build_dir: c:\projects\build-vc140_x64
      wxWidgets_LIBRARIES: $(wxWidgets_ROOT_DIR)\lib\vc140_x64_dll  
      VisualStudioVersion: 14.0
      platform: x64   
    - toolset: mingw
      build_dir: c:\projects\build-gcc530
      wxWidgets_LIBRARIES: $(wxWidgets_ROOT_DIR)\lib\gcc530_dll    

# branches to build
# branches:  

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input
 
# clone directory
clone_folder: '%project_dir%'
 
# scripts to run before build
before_build:
  - ps: git rev-parse HEAD        
  - echo Installing wxWidgets
  - appveyor DownloadFile "https://drive.google.com/uc?export=download&id=0B4Oa5DxgOy2fejFrQ0hYWVUzbWM" -FileName wxWidgets-3.1.1.7z
  - cmd: 7z x wxWidgets-3.1.1.7z -oC:\

build_script:   
  - cmd: cd %project_dir%
  - cmd: build\tools\appveyor.bat               

# after_build:  

# on_finish:
  
# artifacts: